version:  '2'
services:
  cliff:
    image: rahulbot/cliff-clavin:2.6.1
    # build: ./cliff
    ports:
      - "8080:8080"
  mpeds:
    image: mpeds:0.1
    build: ./mpeds
    depends_on:
      - cliff
